### PR TITLE
Wait for transaction to be mined

### LINKED ISSUE #108: Fix transaction response to update data on pages

### PR DESCRIPTION
**Pull request by ghost**
### Description of changes proposed in this pull request:
- Add waitForTransaction method call

### Checks:
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### CODE REVIEW

**Comment by ghost** [comment]
@sali0 I get some errors from functions I did not touch.

**Comment by ind-igo** [comment]
This is fixed on #119

**Comment by ghost** [comment]
@sali0 I added autorefresh of the collateral amount here.

**Comment by ghost** [comment]
@sali0 will implement the content of this pr in his pr. As a result I will close this one.

**Pull request closed without merging**
